output_folder: inputs

2024_mb:
  - dir: /alice/cern.ch/user/a/alihyperloop/outputs/0059/590318/193897
    lbc: 8
  - dir: /alice/cern.ch/user/a/alihyperloop/outputs/0059/590317/193874
    lbc: 5
  - dir: /alice/cern.ch/user/a/alihyperloop/outputs/0059/590316/193865
    lbc: 10

2023_thinned:
  - dir: /alice/cern.ch/user/a/alihyperloop/outputs/0059/590482/194203
    lbc: 8
  - dir: /alice/cern.ch/user/a/alihyperloop/outputs/0059/590481/194193
    lbc: 5
  - dir: /alice/cern.ch/user/a/alihyperloop/outputs/0059/590480/194177
    lbc: 10